### ISSUE TITLE
Better colour scheme!

### ISSUE THREAD

**Issue by KirstieJane** [TeamCalALC/TeamCalALC.github.io#1]
We need to match our website to the GO BEARS Cal colours!

Here are the four theme colours at the moment (in the [`_config.yml` file](https://github.com/TeamCalALC/TeamCalALC.github.io/blob/master/_config.yml#L26)).

```
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
```

Please suggest any other ones you like!
